
export const title = [
    { name: "Mathematician" },
    { name: "Physicist" },
    { name: "Chemist" },
    { name: "Biologist" },
    { name: "Economist" },
    { name: "Business Manager" },
    { name: "Accountant" },
    { name: "Software Developer" },
    { name: "Music Theorist" },
    { name: "Political Scientist" },
    { name: "Lawyer" },
    { name: "Programmer" },
    { name: "Statistician" },
    { name: "Data Analyst" },
    { name: "Financial Analyst" },
    { name: "Operations Research Analyst" },
    { name: "Cryptographer" },
    { name: "Quantitative Analyst" },
    { name: "Mathematics Teacher" },
    { name: "Mathematical Modeler" },
    { name: "Astrophysicist" },
    { name: "Research Scientist" },
    { name: "Nuclear Physicist" },
    { name: "Quantum Physicist" },
    { name: "Medical Physicist" },
    { name: "Optical Physicist" },
    { name: "Acoustics Physicist" },
    { name: "Theoretical Physicist" },
    { name: "Physics Teacher" },
    { name: "Analytical Chemist" },
    { name: "Organic Chemist" },
    { name: "Inorganic Chemist" },
    { name: "Physical Chemist" },
    { name: "Forensic Chemist" },
    { name: "Polymer Chemist" },
    { name: "Biochemist" },
    { name: "Environmental Chemist" },
    { name: "Chemistry Teacher" },
    { name: "Microbiologist" },
    { name: "Zoologist" },
    { name: "Botanist" },
    { name: "Geneticist" },
    { name: "Ecologist" },
    { name: "Marine Biologist" },
    { name: "Immunologist" },
    { name: "Biomedical Scientist" },
    { name: "Biology Teacher" },
    { name: "Financial Economist" },
    { name: "Labor Economist" },
    { name: "Health Economist" },
    { name: "Environmental Economist" },
    { name: "Development Economist" },
    { name: "International Economist" },
    { name: "Behavioral Economist" },
    { name: "Urban Economist" },
    { name: "Economics Teacher" },
    { name: "Entrepreneur" },
    { name: "Marketing Manager" },
    { name: "Financial Manager" },
    { name: "Human Resources Manager" },
    { name: "Operations Manager" },
    { name: "Supply Chain Manager" },
    { name: "Business Analyst" },
    { name: "Strategic Consultant" },
    { name: "Public Relations Specialist" },
    { name: "Market Researcher" },
    { name: "Journalist" },
    { name: "Database Administrator" },
    { name: "Systems Analyst" },
    { name: "Network Administrator" },
    { name: "Computer Science Researcher" },
    { name: "Computer Science Teacher" }
    ]

 export const origin = [
    { name: "United States" },
    { name: "United Kingdom" },
    { name: "Canada" },
    { name: "Australia" },
    { name: "Germany" },
    { name: "France" },
    { name: "Italy" },
    { name: "Spain" },
    { name: "Netherlands" },
    { name: "Switzerland" },
    { name: "Sweden" },
    { name: "Norway" },
    { name: "Denmark" },
    { name: "Finland" },
    { name: "Ireland" },
    { name: "Belgium" },
    { name: "Austria" },
    { name: "Portugal" },
    { name: "Greece" },
    { name: "Japan" },
    { name: "South Korea" },
    { name: "China" },
    { name: "India" },
    { name: "Russia" },
    { name: "Brazil" },
    { name: "Mexico" },
    { name: "Argentina" },
    { name: "Colombia" },
    { name: "Peru" },
    { name: "Chile" },
    { name: "Venezuela" },
    { name: "Ecuador" },
    { name: "South Africa" },
    { name: "Egypt" },
    { name: "Nigeria" },
    { name: "Kenya" },
    { name: "Morocco" },
    { name: "Ethiopia" },
    { name: "Tanzania" },
    { name: "Saudi Arabia" },
    { name: "United Arab Emirates" },
    { name: "Qatar" },
    { name: "Israel" },
    { name: "Iran" },
    { name: "Iraq" },
    { name: "Syria" },
    { name: "Turkey" }
  ]
  